[project]
name = "odmd-subid-cpd"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib<4.0.0",
    "numpy<3.0.0",
    "pandas<3.0.0",
    "requests>=2.32.4",
    "river",
    "scipy<2.0.0",
    "tqdm>=4.67.1",
]

[project.optional-dependencies]
examples = [
    "bayesian-optimization~=1.4.3",
    "jupyter~=1.0.0",
    "notebook~=7.1.2",
]

[tool.pytest.ini_options]
addopts = [
    "--doctest-modules",
    "--doctest-glob=README.md",
    "--ignore=build.py",
    "--ignore=scripts/",
    "--ignore=docs/",
    "--verbose",
    "-ra",
    "-m not datasets and not slow",
    "--color=yes",
    "--junitxml=reports/junit/junit.xml",
    "--html=reports/junit/report/index.html",
    "--cov=.",
    "--cov-report=xml:reports/coverage/coverage.xml",
    "--cov-report=html:reports/coverage/report",
]
doctest_optionflags = [
    "NORMALIZE_WHITESPACE",
    "NUMBER",
    "ELLIPSIS",
    "IGNORE_EXCEPTION_DETAIL",
]
norecursedirs = ["examples", ".*"]

[tool.ruff]
lint.ignore = ["E501"]
lint.select = ["E", "F", "I", "UP"] # https://beta.ruff.rs/docs/rules/

[tool.mypy]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = [
    "river.*",
    "mmh3.*",
    "numpy.*",
    "sklearn.*",
    "pytest.*",
    "pandas.*",
    "scipy.*",
    "graphviz.*",
    "vaex.*",
    "torch.*",
    "sqlalchemy.*",
    "requests.*",
]
ignore_missing_imports = true

[tool.coverage.run]
omit = ["tests/*"]

[tool.coverage.report]
exclude_lines = [
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "class .*\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
]

[tool.uv.sources]
river = { git = "https://github.com/MarekWadinger/river.git" }

[dependency-groups]
app = [
    "streamlit<2.0.0",
]
dev = [
    "commitizen>=4.8.3",
    "mypy>=1.16.1",
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "pytest-html>=4.1.1",
    "ruff>=0.12.1",
    "types-Markdown",
    "types-PyYAML",
    "types-Pygments",
    "types-cachetools",
    "types-colorama",
    "types-decorator",
    "types-defusedxml",
    "types-jsonschema",
    "types-pexpect",
    "types-protobuf",
    "types-pycurl",
    "types-python-dateutil",
    "types-pytz",
    "types-tensorflow",
    "types-toml",
    "types-tqdm",
]
docs = [
    "black<30.0.0",
    "markdown-exec<2.0.0",
    "mkdocs-charts-plugin>=0.0.12",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-include-markdown-plugin<10.0.0",
    "mkdocs-literate-nav>=0.6.2",
    "mkdocs-material<10.0.0",
    "mkdocs-section-index>=0.3.10",
    "mkdocstrings-python<2.0.0",
]
